services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=weatherdb
      - POSTGRES_DB=weatherdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather -d weatherdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Web Application Service (Development)
  webapp:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://weather:weatherdb@postgres:5432/weatherdb
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Generating Prisma Client...' &&
        npx prisma generate &&
        echo 'Running migrations...' &&
        npx prisma migrate dev --name init &&
        echo 'Starting development server...' &&
        npm run dev
      "

volumes:
  postgres-data:  