# Railway Configuration for AeroCast
# This file tells Railway how to build and deploy your services

[build]
builder = "DOCKERFILE"
dockerfilePath = "next-app/dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10