# render.yaml
# Complete deployment configuration for Render

# 1. PostgreSQL Database
databases:
  - name: postgres
    databaseName: weatherdb
    user: weather
    plan: free

# 2. Services
services:
  # Next.js Web Application
  - type: web
    name: aerocast-webapp
    plan: free
    runtime: docker
    dockerfilePath: ./next-app/dockerfile
    dockerContext: ./next-app
    
    # Health check
    healthCheckPath: /
    
    # Environment variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      
      # These need to be added manually in Render dashboard
      - key: NEXTAUTH_SECRET
        sync: false  # Indicates this should be set in dashboard
      
      - key: NEXTAUTH_URL
        sync: false  # Will be your app URL: https://aerocast-webapp.onrender.com
      
      - key: GEOAPIFY_API_KEY
        sync: false
      
      - key: NODE_ENV
        value: production

  # Python Background Worker
  - type: worker
    name: aerocast-worker
    plan: free
    runtime: docker
    dockerfilePath: ./python-worker/Dockerfile
    dockerContext: ./python-worker
    
    # Environment variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString