# render.yaml
# This file tells Render how to build, deploy, and connect your services.

# 1. Define the PostgreSQL Database
databases:
  - name: postgres
    databaseName: weatherdb
    user: weather
    plan: free

# 2. Define the services (your Docker containers)
services:
  # The Next.js Web Application
  - type: web
    name: webapp
    plan: free
    dockerfilePath: ./next-app/dockerfile
    dockerContext: ./next-app
    # Corrected health check property
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  # The Python Background Worker
  - type: worker
    name: worker
    plan: free
    dockerfilePath: ./python-worker/Dockerfile
    dockerContext: ./python-worker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
