
databases:
  - name: postgres 
    databaseName: weatherdb
    user: weather
    plan: free # Use the free database instance type

# 2. Define the Web App and Background Worker
services:
  # The Next.js Web Application
  - type: web
    name: webapp
    plan: free # Use the free web service instance type
    dockerfilePath: ./next-app/dockerfile
    dockerContext: ./next-app
    # Health check path to ensure your app is running
    healthCheck:
      path: /
    # Link environment variables to the database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres # Links to the database defined above
          property: connectionString

  # The Python Background Worker
  - type: worker
    name: worker
    plan: free # Use the free worker instance type
    dockerfilePath: ./python-worker/Dockerfile
    dockerContext: ./python-worker
    # Link environment variables to the database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres # Links to the database defined above
          property: connectionString